language: python

python:
  - "2.7.3" # Ubuntu 12.4LTS (precise) and Debian 7 LTS (wheezy)
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"

install:
  - travis_retry bash test/travis_setup.sh

script:
  - python test/testall.py fast

notifications:
  irc: "irc.freenode.org#bottlepy"
  on_success: "never"
