language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"

install:
  - sudo apt-get install -qq libev-dev
  - pip install -r .travis-requirements.txt
  - pip install .

script: make test

